/**
 * Slugify, ported from the Postgres `slugify()` it replaces.
 *
 * Appwrite has no stored procedures, so this moves into the application.
 * The behaviour has to match what the SQL did, because the seed slugs
 * were generated by it and a spot's slug is its permanent URL.
 *
 * Accent folding happens first and is not decoration: this index is
 * mostly places whose names carry diacritics. Strip non-[a-z0-9] before
 * folding and "vlorë" becomes "vlor", "å" disappears entirely.
 *
 * `normalize("NFD")` decomposes a letter into its base plus a combining
 * mark, so removing the marks leaves the base — the same result as the
 * SQL's hand-written translate() table, without maintaining the table.
 */
export function slugify(input: string): string {
  return (
    (input ?? "")
      .normalize("NFD")
      .replace(/[̀-ͯ]/g, "")
      .toLowerCase()
      // Letters NFD cannot decompose, because they are not accented forms
      // of an ASCII letter. The SQL table covered these explicitly.
      .replace(/ø/g, "o")
      .replace(/đ|ð/g, "d")
      .replace(/þ/g, "t")
      .replace(/ß/g, "s")
      .replace(/æ/g, "a")
      .replace(/œ/g, "o")
      .replace(/ł/g, "l")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/-{2,}/g, "-")
      .replace(/^-+|-+$/g, "")
  );
}

/**
 * Appwrite caps a row ID at 36 characters, and a slug is not the row ID
 * partly because of that. It is still worth a ceiling: a slug is a URL
 * people type and share, and an 80-character name should not produce an
 * 80-character path.
 */
export const SLUG_MAX = 60;

/**
 * The slug for a *new* submission.
 *
 * Note that the seeded spots' slugs are editorial, not generated —
 * "gjipe cove" is filed under `gjipe-beach-approach` because that is what
 * people search for. Twelve of the fourteen differ from what this would
 * produce, which is correct and deliberate: the seeder writes the slug it
 * is given and never regenerates one. A slug is a permanent URL, so it is
 * chosen once and then left alone.
 */
export function toSlug(name: string): string {
  const base = slugify(name).slice(0, SLUG_MAX).replace(/-+$/, "");
  // Every name in the index is at least three characters, but a name made
  // entirely of characters this strips would otherwise produce "".
  return base || "spot";
}
