-- ---------------------------------------------------------------------
-- Seed spots.
--
-- GENERATED by scripts/generate-seed-sql.mjs from src/lib/data/spots.ts.
-- Do not edit by hand — regenerate with `npm run seed:sql`.
--
-- Idempotent: re-running updates existing rows by slug rather than
-- erroring or duplicating, so it is safe to replay against a database
-- that already has some of these.
-- ---------------------------------------------------------------------

set search_path = public, extensions;

-- gjipe cove (vlorë, albania)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'gjipe-beach-approach', 'gjipe cove', 'vlorë', 'albania',
  40.1519, 19.7361,
  'shore', 'moderate', 'open',
  'a canyon walks you down to a beach with no road to it.',
  'the ionian coast has a hundred beaches you can park at. this isn''t one. you leave the car on the ridge and walk down a dry canyon for about forty minutes, and the canyon does the whole thing for you — it narrows, the limestone goes vertical, and then it opens onto sand. because there''s no road, the crowd tops out at maybe thirty people in august and zero the rest of the year. there''s a bunker at the north end left over from hoxha, half sunk in the sand, which is exactly as photogenic as it sounds.',
  'the canyon floor is loose scree in two places. going down is fine; coming back up in flip-flops is not.',
  'may–june, or late september. july–august is hot and airless.',
  2.1,
  '[{"src":null,"alt":"the canyon narrows on the walk down to gjipe cove"},{"src":null,"alt":"concrete bunker half buried at the north end of the beach"},{"src":null,"alt":"limestone walls above the cove at evening light"}]'::jsonb,
  '2026-03-11'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- mena creek overflow (queensland, australia)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'paronella-park-overflow', 'mena creek overflow', 'queensland', 'australia',
  -17.6558, 145.9925,
  'ruin', 'easy', 'permit',
  'a spanish castle folly rotting into the rainforest.',
  'a catalan immigrant spent the 1930s building a mock castle, a ballroom and a hydro plant in the middle of far north queensland rainforest, and then cyclones and fire spent the next ninety years taking it apart. what''s left is concrete stairways going into the canopy and a turbine house that still runs. the state has it now, which means you pay and it''s signposted — but go at last light when the tour groups have cleared and it stops feeling managed.',
  'the concrete is ninety years old and permanently wet. the moss on the lower stairs is genuinely slick.',
  'dry season, may–october. last entry, not first.',
  0.4,
  '[{"src":null,"alt":"concrete stairway disappearing into rainforest canopy"},{"src":null,"alt":"the ruined ballroom wall with tree roots through it"}]'::jsonb,
  '2026-02-27'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- kolmanskop drift houses (karas, namibia)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'kolmanskop-drift', 'kolmanskop drift houses', 'karas', 'namibia',
  -26.7044, 15.2306,
  'ruin', 'easy', 'permit',
  'a diamond town the desert is slowly filling in.',
  'german colonial houses abandoned in the 1950s when the diamonds ran out, sitting in the sperrgebiet where the dunes have been walking through the doors ever since. some rooms are waist-deep in sand. the light through the broken windows in the first hour after sunrise is the entire reason to be there, which is why the photography permit exists and why it costs more than the standard one. worth it.',
  'it sits inside a restricted diamond area — you cannot freelance this one. permit or don''t go.',
  'sunrise. the standard permit doesn''t start early enough.',
  0.3,
  '[{"src":null,"alt":"sand drifted through a doorway into a bare room"},{"src":null,"alt":"peeling ochre wall with desert light across it"},{"src":null,"alt":"dune spilling into the corner of a colonial house"}]'::jsonb,
  '2026-01-09'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- vikos balcony (epirus, greece)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'vikos-balcony', 'vikos balcony', 'epirus', 'greece',
  39.9847, 20.7439,
  'viewpoint', 'hard', 'open',
  'an unmarked ledge over the deepest gorge in europe.',
  'everyone drives to the oxya viewpoint, takes the photo from behind the railing and leaves. an hour further along the rim, past where the marked path gives up, there''s a limestone shelf with nothing between you and nine hundred metres of air. no railing, no sign, no one. the gorge runs north-south so the light moves across the far wall all afternoon and the whole thing changes colour about four times.',
  'no railing and no phone signal. the last kilometre is unmarked — if you are not comfortable route-finding, stop at oxya.',
  'late afternoon, april–october. the rim is ice in winter.',
  5.8,
  '[{"src":null,"alt":"limestone shelf above the vikos gorge with no railing"},{"src":null,"alt":"afternoon light moving across the far gorge wall"}]'::jsonb,
  '2026-02-02'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- williamson's lower tunnels (liverpool, united kingdom)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'williamson-tunnels-lower', 'williamson''s lower tunnels', 'liverpool', 'united kingdom',
  53.4021, -2.9558,
  'underground', 'moderate', 'permit',
  'brick caverns dug for no known reason, still being excavated.',
  'a nineteenth-century tobacco merchant employed men for decades to dig an enormous network of brick-vaulted tunnels under edge hill, and nobody has ever established why. no ore, no drainage, no cellar. volunteers have been digging the infill out by hand since the 1990s and are still not at the bottom. the guided section is a fraction of it; the rest is rubble and speculation.',
  'hard hat sections are hard hat sections for a reason. the volunteers will tell you where not to stand; listen.',
  'year round — it''s 12°c down there regardless.',
  0.1,
  '[{"src":null,"alt":"brick vaulted tunnel disappearing into darkness"},{"src":null,"alt":"excavated rubble face at the working end of the tunnel"}]'::jsonb,
  '2026-01-22'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- behind salto ventoso (rio grande do sul, brazil)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'salto-ventoso-back', 'behind salto ventoso', 'rio grande do sul', 'brazil',
  -29.0447, -51.3506,
  'water', 'moderate', 'permit',
  'a path that runs behind the waterfall, not in front of it.',
  'the basalt undercut here is deep enough that a walkway runs the full width behind the falling water. you come out the other side soaked and half deaf. it''s on private land and the family that owns it charges a small fee, which is the only reason it hasn''t been ruined — numbers stay low and the path stays unimproved.',
  'the ledge behind the falls is permanently wet basalt. hold the chain, and don''t do it in trainers.',
  'after rain, when the curtain is full. midday for light through the water.',
  1.2,
  '[{"src":null,"alt":"the walkway behind the waterfall curtain"},{"src":null,"alt":"light through falling water from the undercut"}]'::jsonb,
  '2026-03-30'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- hafnarfjall north spur (vesturland, iceland)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'hafnarfjall-spur', 'hafnarfjall north spur', 'vesturland', 'iceland',
  64.5203, -21.9319,
  'viewpoint', 'serious', 'open',
  'a steep unmarked spur above borgarfjörður, wind permitting.',
  'the tourist route up hafnarfjall is a slog on loose scree. the north spur is a scramble on better rock with a genuine ridge line at the top and a view down the whole fjord. it is not maintained, not marked, and not a good idea in wind — which in this part of iceland is most days. check the forecast, and mean it.',
  'wind. gusts here regularly hit speeds that will take you off the ridge. if it''s above 15m/s at the car park, don''t start.',
  'june–august, and only on a settled forecast.',
  4.4,
  '[{"src":null,"alt":"the north spur ridge line above borgarfjörður"},{"src":null,"alt":"loose basalt scramble on the upper spur"}]'::jsonb,
  '2026-04-15'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- canfranc long platform (aragón, spain)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'canfranc-platform', 'canfranc long platform', 'aragón', 'spain',
  42.7539, -0.5203,
  'transit', 'easy', 'grey',
  'an enormous dead border station in the middle of the pyrenees.',
  'built in 1928 to a scale that made no sense even then — a platform the better part of a quarter mile long, in a valley with almost nobody in it. a bridge collapse closed the french side in 1970 and it has been mostly dead since. the main building has been restored into a hotel, but the sidings, the customs sheds and the far end of the platform are still exactly as abandoned as they were.',
  'the restored end is a working hotel; the far end is unfenced railway land. nobody stops you, but it isn''t yours.',
  'any. autumn for the valley colour.',
  0.6,
  '[{"src":null,"alt":"the quarter-mile platform at canfranc receding into fog"},{"src":null,"alt":"derelict customs shed beside overgrown sidings"},{"src":null,"alt":"the station facade from the valley road"}]'::jsonb,
  '2026-02-14'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- upstream of hamilton pool (texas, united states)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'hamilton-pool-upstream', 'upstream of hamilton pool', 'texas', 'united states',
  30.3424, -98.1266,
  'water', 'moderate', 'grey',
  'the limestone creek above the reserved, ticketed grotto.',
  'hamilton pool itself now needs a timed reservation months out. the creek that feeds it, above the reserve boundary, does not — and the same limestone shelving and the same clear green water run for a good distance upstream. it is emphatically not the famous collapsed grotto, and it is also not full of people who booked in march.',
  'flash flooding is the real hazard in this drainage, not the walk. do not go in on a storm forecast, upstream or not.',
  'spring, when the creek is actually running.',
  1.7,
  '[{"src":null,"alt":"limestone shelves and clear water on the creek upstream"},{"src":null,"alt":"cypress roots along the creek bank"}]'::jsonb,
  '2026-03-19'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- nagasaki seawall view (nagasaki, japan)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'gunkanjima-shadow', 'nagasaki seawall view', 'nagasaki', 'japan',
  32.6277, 129.7386,
  'shore', 'easy', 'open',
  'the shore angle on hashima that the boat tours don''t give you.',
  'landing on hashima is weather-dependent, heavily restricted and confined to a short walkway. what nobody mentions is that from a stretch of seawall on the nomozaki side, on a clear afternoon, you get the whole island in profile with the sun behind it — the silhouette that makes it look like the battleship it''s named after. free, and you can stay as long as you like.',
  'the seawall is exposed and the swell comes up fast on a south wind. stay off the lower blocks.',
  'clear afternoons. winter has the sharpest air.',
  0.8,
  '[{"src":null,"alt":"hashima island in profile from the nomozaki seawall"},{"src":null,"alt":"swell breaking against the seawall blocks"}]'::jsonb,
  '2026-01-30'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- beelitz north stairwell (brandenburg, germany)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'beelitz-stairwell', 'beelitz north stairwell', 'brandenburg', 'germany',
  52.2617, 12.9192,
  'ruin', 'easy', 'private',
  'the sanatorium wing that was never put on the treetop walk.',
  'most of beelitz-heilstätten has been tidied into a paid attraction with an elevated walkway. the north wing has not. it is fenced, it is monitored, and it is listed here for the record rather than as a recommendation — the interior is genuinely unsafe and the security is real. the legal parts are still worth the trip.',
  'posted private with active security and unsafe floors. we log it; we don''t recommend entering it.',
  'n/a — go to the ticketed section instead.',
  1.1,
  '[{"src":null,"alt":"the north wing facade behind fencing"},{"src":null,"alt":"the sanctioned treetop walkway over the sanatorium"}]'::jsonb,
  '2026-02-20'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- quilotoa far rim (cotopaxi, ecuador)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'quilotoa-far-rim', 'quilotoa far rim', 'cotopaxi', 'ecuador',
  -0.8608, -78.9014,
  'viewpoint', 'hard', 'open',
  'the two-thirds of the crater rim nobody walks.',
  'the viewpoint at the village end of the quilotoa crater is full by nine in the morning. the rim trail runs the whole way round — about ten kilometres of it — and almost nobody does more than the first twenty minutes. the far side is exposed, has real drop-offs, and gives you the lake from an angle that isn''t in any of the photos.',
  '3,900m. the altitude, not the distance, is what turns this one around — and there is no water on the rim.',
  'start at first light. cloud closes the crater by early afternoon.',
  9.6,
  '[{"src":null,"alt":"the crater lake from the far rim in morning light"},{"src":null,"alt":"exposed section of the rim trail with drop-offs"}]'::jsonb,
  '2026-04-06'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- maunsell forts approach (kent, united kingdom)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'maunsell-approach', 'maunsell forts approach', 'kent', 'united kingdom',
  51.4756, 1.0472,
  'structure', 'serious', 'grey',
  'wartime sea forts standing in the thames estuary on stilts.',
  'clusters of steel towers built in 1942 to shoot at aircraft, left standing in the estuary ever since, rusting on their legs. you cannot land — the structures are unsound and the ladders are gone. what you can do is get a charter out of whitstable on a flat day and sit underneath them, which is more unsettling than landing would be.',
  'open estuary with serious tidal streams and no shelter. this is a boat trip, not a walk — go with someone who knows the water.',
  'flat calm, neap tides, summer only.',
  0,
  '[{"src":null,"alt":"the maunsell forts standing on rusted stilts"},{"src":null,"alt":"view up at the underside of a fort tower"}]'::jsonb,
  '2026-05-01'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- wieliczka lower chambers (lesser poland, poland)
insert into public.spots (
  slug, name, region, country, lat, lng,
  category, difficulty, access,
  summary, description, watch_out, best_window, walk_in_km, photos, created_at
) values (
  'wieliczka-lower-chamber', 'wieliczka lower chambers', 'lesser poland', 'poland',
  49.9831, 20.0544,
  'underground', 'moderate', 'permit',
  'the miners'' route, three hundred metres down, not the tourist loop.',
  'everyone does the tourist route past the salt chapel. the miners'' route goes deeper, gives you a lamp and a detector, and takes you through unlit working chambers where you climb rather than walk. same mine, entirely different experience, and it books out far less because most people don''t know it exists.',
  'three hours underground with real ladders. not one for anyone shaky on climbing in the dark.',
  'year round. 14°c and no weather, ever.',
  2.8,
  '[{"src":null,"alt":"unlit working chamber on the miners'' route"},{"src":null,"alt":"timber supports in a lower salt gallery"}]'::jsonb,
  '2026-03-25'::timestamptz
)
on conflict (slug) do update set
  name = excluded.name,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  difficulty = excluded.difficulty,
  access = excluded.access,
  summary = excluded.summary,
  description = excluded.description,
  watch_out = excluded.watch_out,
  best_window = excluded.best_window,
  walk_in_km = excluded.walk_in_km,
  photos = excluded.photos;

-- ------------------------------------------------------------- notes --

delete from public.spot_notes
where spot_id in (select id from public.spots where slug in (
  'gjipe-beach-approach',
  'paronella-park-overflow',
  'kolmanskop-drift',
  'vikos-balcony',
  'williamson-tunnels-lower',
  'salto-ventoso-back',
  'hafnarfjall-spur',
  'canfranc-platform',
  'hamilton-pool-upstream',
  'gunkanjima-shadow',
  'beelitz-stairwell',
  'quilotoa-far-rim',
  'maunsell-approach',
  'wieliczka-lower-chamber'
));

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'marta_k', 'walked it at 7am to beat the heat — had the whole beach for two hours. the small bar at the bottom opens around 10 and takes cash only.', '2026-06-02'::date
from public.spots where slug = 'gjipe-beach-approach';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'duncan', 'canyon had running water in april, ankle deep in one spot. not a problem, just wear something you don''t mind soaking.', '2026-04-18'::date
from public.spots where slug = 'gjipe-beach-approach';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'reeve', 'ticket covers you for 24h and includes the night walk. do both — the place is completely different lit.', '2026-05-21'::date
from public.spots where slug = 'paronella-park-overflow';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 's_oyelaran', 'buy the sunrise permit in lüderitz the day before, not at the gate. they cap the numbers.', '2026-01-14'::date
from public.spots where slug = 'kolmanskop-drift';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'petra.h', 'the turn off the marked trail is at a cairn about 40min past oxya, easy to walk straight past. gpx is worth having.', '2026-05-30'::date
from public.spots where slug = 'vikos-balcony';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'andreas_v', 'went in march, still snow on the rim path in shade. would not do it again that early.', '2026-03-08'::date
from public.spots where slug = 'vikos-balcony';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'j_okafor', 'the volunteer-run entrance does a longer tour than the heritage centre one and costs less. book by email, they''re slow to reply but they do.', '2026-04-04'::date
from public.spots where slug = 'williamson-tunnels-lower';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'lu_ferreira', 'dry spell in june meant the curtain was thin — still good but go after rain if you can time it.', '2026-06-11'::date
from public.spots where slug = 'salto-ventoso-back';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'eirik', 'turned back 200m from the top on a ''calm'' forecast day. it funnels. no regrets.', '2026-07-19'::date
from public.spots where slug = 'hafnarfjall-spur';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'mireia', 'the hotel bar will let you walk the restored hall without being a guest. the interesting half is north of it anyway.', '2026-05-09'::date
from public.spots where slug = 'canfranc-platform';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'dez', 'creek was dry in august last year — completely pointless trip. april was perfect.', '2026-04-27'::date
from public.spots where slug = 'hamilton-pool-upstream';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'haru_t', 'bus from nagasaki takes about an hour and drops you close. go late — the island is backlit after 3pm.', '2026-02-08'::date
from public.spots where slug = 'gunkanjima-shadow';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'kb_', 'for what it''s worth the paid section covers the best surviving stairwell anyway. not worth a fine.', '2026-03-02'::date
from public.spots where slug = 'beelitz-stairwell';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'nadia.r', 'took 5.5h including stops, coming from sea level two days earlier. underestimated it badly. carry more water than you think.', '2026-06-24'::date
from public.spots where slug = 'quilotoa-far-rim';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'tomasz_w', 'two charters out of whitstable run it. neither will go if there''s any north in the wind, and they''re right not to.', '2026-07-02'::date
from public.spots where slug = 'maunsell-approach';

insert into public.spot_notes (spot_id, author, body, noted_on)
select id, 'agnieszka', 'book the miners'' route online a week ahead. english departures are only twice a day.', '2026-05-16'::date
from public.spots where slug = 'wieliczka-lower-chamber';
